project_id = "tmykvewbmhqyuzsdaifo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://tmykvewbmhqyuzsdaifo.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_password_change_enabled = true
enable_signup = true

[db]
port = 54322

[edge_runtime]
enabled = true
port = 54323

[functions.generate-story]
verify_jwt = true

[functions.generate-story-image]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.structured-story-flow]
verify_jwt = true

[functions.get-user-stories]
verify_jwt = true

[functions.manage-characters]
verify_jwt = true