// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmykvewbmhqyuzsdaifo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRteWt2ZXdibWhxeXV6c2RhaWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MjUwMjQsImV4cCI6MjA2ODMwMTAyNH0.XnjxHIVdlGI6XTghcQkStdTnJb2SFaqVomm_MHJ1yqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});